module.exports = {
    MSG_INTERNAL_SERVER_ERROR: 'Internal server error.',
    MSG_NO_RECORDS_FOUND: 'No records found.',
    MSG_EXCEED_LIMIT_FAV_CLUB: 'you can set only 5 clubs as favorite at a time',
    MSG_DATE_OF_BIRTH_INVALID: 'you must be atleast 18 years old to continue',
    MSG_DATE_OF_BIRTH_INVALID_THIRTEEN: 'you must be atleast 13 years old to continue',
    MSG_EMAIL_NOT_FOUND: 'Email not found.',
    MSG_PASSWORD_MISSING: 'User not found.',
    MSG_USER_MISSING: 'User not found.',
    MSG_EMAIL_EXIST: 'Email id already exists.',
    MSG_SUCCESS: 'success',
    MSG_INSERT_FAILED: 'INSERTION FAILED',
    MSG_PHONE_NOT_FOUND: 'This phone number is not linked with the account.',
    MSG_UNAUTHORIZED: 'Unauthorized',
    NOT_FOUND: 'Route not found.',
    TOKEN_EXPIRED: 'Invalid or expired email token. Please request a new one.',
    EMAIL_VERIFIED: 'Your email address has been successfully verified.',
    EMAIL_NOT_VERIFIED: 'You must have verified your email in order to continue further.',
    MSG_USER_NOT_REGISTERED: "We couldn't find your account.",
    MSG_OPEN_IN_MOBILE: 'Kindly open this URL from mobile.',
    MSG_ALREADY_BOOKED: 'Already booked.',
    MSG_NOT_AUTHORIZED_FOR_BOOKING: 'You are not authorized to book a class.',
    MSG_UNABLE_TO_CREATE: 'Unable to create your account.',
    MSG_INVALID_PHONE: 'Invalid phone number.',
    MSG_NO_CLUB_FOUND: 'No club found.',
    MSG_NO_BOOKING: 'No booking created by the app.',
    MSG_NO_BOOKING_FOUND: 'No booking found.',
    MSG_BOOKING_WITH_SAME_TIME_FOUND: 'You already have a booking for that time.',
    MSG_NO_BOOKING_FOUND_AGAINST_CLASS: 'You are not registered for this class.',
    MSG_BOOKING_CANCELLED_ALREADY: 'You have already cancelled this booking.',
    MSG_BOOKING_CANNOT_BE_CANCELLED: 'Booking can not be cancelled.',
    MSG_BIOMETRIC_TOKEN_INVALID: 'Biometric token is invalid or expired. Please try to login with your password.',
    MSG_UNABLE_TO_GENERATE_BIOMETRIC_TOKEN: 'Unable to generate access token.',
    MSG_REQ_PARA_MISSING: 'Request Parameter(s) Missing.',
    MSG_PW_CHANGED: 'Password changed successfully.',
    MSG_PW_NOT_MATCHING: 'Current Password Incorrect',
    MSG_RECORDS_UPDATED: 'Record(s) updated successfully.',
    MSG_PROFILE_PICTURE_UPDATED: ' Profile picture updated successfully.',
    MSG_PW_CAN_NOT_BE_SAME: 'Password can not be same as last one.',
    MSG_INVALID_REFRESH_TOKEN: 'Invalid refresh token.',
    MSG_INVALID_CLUB: 'Invalid Club.',
    MSG_ACCOUNT_ASSOCIATED_WITH_DIFF_CLUB: 'Your account is associated with different location.',
    MSG_INVALID_CATEGORY: 'Invalid type.',
    MSG_TYPE_REQUIRED: 'Type is required.',
    MSG_INVALID_MEMBERSHIPTYPE: 'Invalid membershiptype found.',
    MSG_USER_AGREEMENT_EXPIRED: 'Your agreement is expired.',
    MSG_ACTIVATE_MEMBERSHIP: 'Please activate your membership to book a class.',
    MSG_NO_MATCH_FOUND: 'No records found with the search criteria. Please contact your club.',
    MSG_PHONE_FORMAT: 'Phone format should be (000) 000-0000.',
    MSG_ALREADY_FOUND_ACTIVE_PASSWORD: 'Oops! user already have an active password.',
    MSG_MEMBER_NOT_FOUND: 'Member not found.',
    MSG_INVALID_EVENT_ID: 'No such event found.',
    MSG_USER_WILL_BE_NOTIFIED: 'You will be notified.',
    MSG_ALREADY_ENROLLED_FOR_THIS_CLASS_NOTIFICATION: "You're already enrolled for this Notification.",
    MSG_FCM_TOKEN_SET: 'FCM Token set successfully.',
    MSG_BIOMETRIC_NOT_OPT_IN: 'Biometric login is disabled for user.',
    MSG_NO_PROSPECT_FOUND: 'We did not find matching 7-Day pass record. Would you like to create a new 7-Day Pass Account?',
    MSG_7_DAY_PASS_USED: 'You already have used 7-Day free trial under this club.',
    MSG_APP_ACCOUNT_DELETED: 'Your account has been deleted.',
    MSG_UNABLE_TO_DELETE_ACCOUNT: 'Unable to delete your account.',
    MSG_MEMBER_UNAUTHORIZED: 'Member unauthorized', // Used when member linked club is inactive
    MSG_RECOVERY_BOOKED_FOR_TODAY: 'You already have a booking for this Amenity for today.',
    MSG_UNABLE_TO_REQUEST_FREEZE_ACCOUNT: 'Unable to request for freeze account. Please try again',
    MSG_FREEZE_ACCOUNT_MEMBER_ONLY: 'Only members can freeze their accounts.',
    MSG_FREEZE_DOC_REQUIRED: 'Documents Required.',
    MSG_FREEZE_DOC_MAX: 'Maximum 5 documents can be uploaded.',
    MSG_FREEZE_ONLY_ACTIVE_MEMBER: 'Only active members can request to freeze their membership.',
    MSG_CANCEL_MEMBERSHIP_ONLY_ACTIVE_MEMBER: 'Only active members can request to cancel their membership.',
    MSG_UNABLE_TO_DOWNGRADE: 'You are already at base membership package you cannot downgrade further.',
    MSG_UNABLE_TO_UPGRADE: 'You already have highest membership package you cannot upgrade further.',
    MSG_UNABLE_SAME_PLAN: 'You have a similar plan activated.',
    MSG_UNABLE_TO_UPGRADE_CHANGE_PLAN: 'You cannot upgrade to a lower plan.',
    MSG_UNABLE_TO_DOWNGRADE_CHANGE_PLAN: 'You cannot downgrade to a higher plan.',
    MSG_FOUND_FREEZE_REQUEST: 'You already have requested for your account freeze within the given duration.',
    MSG_FOUND_CANCEL_REQUEST: 'You already have requested for cancelling your membership.',
    MSG_FOUND_UPGRADE_REQUEST: 'You have already requested to upgrade your membership.',
    MSG_FOUND_DOWNGRADE_REQUEST: 'You have already requested to downgrade your membership.',
    MSG_UNFREEZE_ONLY_FREEZE_MEMBER: 'Only freeze member can unfreeze their membership.',
    MSG_FREEZE_NOT_ALLOWED: 'You cannot request to freeze your account for more than a year.',
    MSG_AGREEMENT_CREATED: 'Agreement Created Successfully.',
    MSG_SOMETHING_WENT_WRONG: 'Something went wrong.',
    MSG_CC_NOT_VALID: 'CreditCard number is invalid.',
    MSG_CVV_NOT_VALID: 'CVV code length is not valid for the given credit card type.',
    MSG_BANK_ROUTING_NO_NOT_VALID: 'Routing number should be exactly 9 digits.',
    MSG_ACCOUNT_TYPE: 'Account type should be either savings or checking.',
    MSG_INVALID_STATE_CODE: 'State format should be valid two alpha character state or province abbreviation.',
    MSG_INVALID_PLANID: 'Invalid Plan ID.',
    MSG_INVALID_CC_LASTNAME: "Expected lastname format between 1 and 19 alphanumeric characters, apostrophes('), hyphens(-), or spaces and must begin with an alpha character.",
    MSG_INVALID_CC_FIRSTNAME: "Expected firstname format between 1 and 15 alphanumeric characters, apostrophes('), hyphens(-), or spaces and must begin with an alpha character or space.",
    MSG_INVALID_ADDRESS: 'Expected address format between 1 and 44 alphanumeric characters, spaces, forward slashes(/), or pound signs(#).',
    MSG_MEMBER_DETAILS_RETRIEVED: 'Member details retrieved.',
    MSG_NO_PARAMETER_PASSED: 'No parameter(s) passed to update.',
    MSG_CHECKIN_NOT_FOUND: 'Try check into the club, then book this recovery amenity.',
    MSG_CHECKIN_NOT_FOUND_CLASS: 'Try check into the club, then book this class.',
    MSG_NOT_ALLOWED_TO_BOOK_MORE: 'You have exceeded the limit for booking, Try again in an hour.',
    MSG_BOOK_ONLY_ONCE: 'You are not allowed to book more than once in a day.',
    MSG_VIEW_AGREEMENT_DOCUMENT_ERROR: 'Member agreement is not available.',
    MSG_MEMBER_CLUB_CHECKIN_SUCCESS: 'Checked in successfully.',
    MSG_MEMBER_CLUB_UNABLE_TO_CHECKIN: 'Unable to check in, please try again.',
    MSG_MEMBER_RECORD_NOT_FOUND: 'Couldn\'t find the member record',
    MSG_REPORT_EMAIL_CONTENT: 'Please see below for any attached reports.',
    MSG_APP_VERSION_NOT_FOUND: 'No data found in the database.',
    MSG_DEVICE_NOT_SUPPORTED: 'Device not supported.',
    MSG_INVALID_PROMO_CODE: 'That promo code is not valid for this location or plan. Please select the correct membership or promo code.',
    MSG_ACTIVITY_NOT_FOUND: 'Activity is not available',
    MSG_PARSE_FAILED: 'entity.parse.failed',
    MSG_INVALID_JSON: 'Invalid JSON format',
    MSG_NOT_ALLOWED_TO_BOOK_RECOVERY: 'You are not allowed to book this recovery.',
    MSG_NOT_ALLOWED_TO_BOOK_CLASS: 'You are not allowed to book classes.',
    MSG_MEMBER_ID_NOT_AVAILABLE: 'Member id not available.',
    MSG_PERKVILLE_INVALID_CODE: 'Invalid code or code expired.',
    MSG_PERKVILLE_INVALID_TOKEN: 'Your Perkville token is invalid or has expired.',
    MSG_RECORD_ISSUE: 'Following record(s) have issues.',
    MSG_AUTHORIZE_PERKVILLE: 'Please authorize the perkville account.',
    MSG_MINORS_NOT_ALLOWED_SELF_SERVICE: 'Minors are not allowed to use member self services.',
    MSG_CLUB_EVENT_OVERLAPPING: 'You cannot have overlapping bookings at two separate club locations',
    MSG_CLASS_BOOKING_CLASH: 'You have an existing class reservation during this time. Please cancel first before booking a new one.',
    MSG_7_DAY_PASS_REDEEMED: "Whoops! You've already redeemed a 7-day pass.Join today - we'd love to have you!",
    MSG_BLOCKED_ONBOARDING: 'User is temporarily blocked from upgrading new membership.',
    MSG_UNABLE_SEND_VERIFICATION_CODE: 'Unable to send verification code.',
    MSG_INVALID_VERIFICATION_CODE: 'Invalid or expired verification code.',
    MSG_NO_RECORDS_FOUND_FOR_LINK_NEW_MEMBERSHIP: "Sorry, but no data matches with the information you've entered.",
    MSG_NO_CLASS_BOOKINGS_CREATED: "You don't have any classes booked yet!",
    MSG_NO_RECOVERY_BOOKINGS_CREATED: "You don't have any recoveries booked yet!",
    MSG_ALREADY_JOINED_CHALLENGE: 'You have already joined this challenge!',
    MSG_INVALID_CHALLENGE: 'No challenge found.',
    MSG_NOT_ENROLLED_IN_CHALLENGE: 'You are not enrolled in this challenge.',
    MSG_CANT_DELETE_ANONYMOUS_USER: 'This user cannot be deleted.',
    MSG_NOT_CHECKED_IN_FOR_BUDDY_ACTIVATION: 'You must be checked in to the club to activate your buddy.',
    MSG_BUDDY_ALREADY_ACTIVE: 'Buddy is already active.',
    MSG_ONE_BUDDY_ALREADY_ACTIVE: "Oops! You're limited to one active buddy at a time.",
    MSG_BUDDY_ACTIVATED: 'Buddy activated successfully.',
    MSG_BUDDY_DEACTIVATED: 'Buddy deactivated successfully.',
    MSG_USER_IS_NOT_BUDDY: 'User is not a buddy.',
    MSG_BUDDY_DELETED_SUCCESSFULLY: 'Buddy removed successfully.',
    MSG_PERKVILLE_ADMIN_TOKEN_EXPIRED: 'Perkville token expired.',
    MSG_LOGIN_TOKEN_EXPIRED: 'You have been logged out due to security reasons. Please login again.',
    MSG_MEMBERSHIP_CANCELLATION_NOT_ALLOWED: 'You cannot cancel your membership here. Please visit the front desk for further assistance.',
    MSG_MEMBER_CANCELLATION_NOTE: 'Membership canceled via the Chuze app.'
  }
  