name: GPT Code Review

on:
  pull_request:
    branches:
      - master  # Specify the branch to run on

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # Step 1: Get the Git Diff with Line Numbers
      - uses: GrantBirki/git-diff-action@v2.4.0  # Action to gather the git diff of the pull request
        id: git-diff
        with:
          raw_diff_file_output: diff.txt
          file_output_only: "true"
          include_line_numbers: "true"  # Ensure line numbers are captured

      # Step 2: Perform Code Review With GPT-4
      - name: Perform Code Review With GPT-4
        id: code_review_suggestions
        run: |
          # Get the code changes
          changed_code=$(cat ${{ steps.git-diff.outputs.raw-diff-path }})
          
          echo "PR Changes: $changed_code"
          
          # Escape newlines and double quotes in the changed_code
          escaped_code=$(echo "$changed_code" | jq -s -R -r @json)
          echo "Escaped code for request: $escaped_code"
          
          # Log the request being sent to GPT-4
          echo "Making request to GPT-4 with escaped code"
          request_payload="{
              \"messages\": [
                { \"role\": \"system\", \"content\": \"Review the code and provide actionable comments only if necessary. If no suggestion is required, reply with 'all good'.\" },
                { \"role\": \"user\", \"content\": $escaped_code }
              ]
            }"
          echo "Request Payload: $request_payload"
          
          # Make the request to GPT-4
          response=$(curl -s -X POST https://code-guardians.openai.azure.com/openai/deployments/code-guardians-gpt-4o/chat/completions?api-version=2024-06-01\
            -H "Content-Type: application/json" \
            -H "api-key: ${{ secrets.OPEN_AI_KEY }}" \
            -d "$request_payload")
          
          # Log the raw response from GPT-4
          echo "Response from GPT-4: $response"
          
          # Extract the code review suggestions from the response
          code_review_suggestions=$(echo "$response" | jq -r '.choices[0].message.content')
          
          # Log the suggestions received from GPT-4
          echo "GPT-4 Code Review Suggestions: $code_review_suggestions"
          
          # Save the suggestions to a file
          echo "$code_review_suggestions" > code_suggestions.txt

      # Step 3: Add Code Suggestions to Specific Lines
      - name: Add Code Suggestions to Specific Lines
        run: |
          while IFS= read -r line; do
            line_number=$(echo "$line" | awk '{print $1}')  # Extract line number from diff
            comment=$(echo "$line" | awk '{$1=""; print $0}')  # Extract comment from diff
            echo "Adding comment on line $line_number: $comment"
            
            # Escape the comment for JSON format
            escaped_comment=$(echo "$comment" | jq -s -R -r @json)
            
            # Post the comment to the specific line in the PR diff
            curl -s -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/comments \
              -d "{
                \"body\": $escaped_comment,
                \"commit_id\": \"${{ github.event.pull_request.head.sha }}\",
                \"path\": \"index.js\",  # Replace with the actual path of the file
                \"position\": $line_number
              }"
          done < code_suggestions.txt
